import AppKit
import Foundation

final class ClipboardWatcher {
  private let state: AppState
  private let config: AppConfig
  private var timer: DispatchSourceTimer?

  init(state: AppState, config: AppConfig) {
    self.state = state
    self.config = config
  }

  func start() {
    if timer != nil { return }

    let timer = DispatchSource.makeTimerSource(queue: DispatchQueue.global(qos: .utility))
    timer.schedule(
      deadline: .now() + config.clipboardPollSeconds,
      repeating: config.clipboardPollSeconds
    )
    timer.setEventHandler { [weak self] in
      self?.poll()
    }
    self.timer = timer
    timer.resume()
  }

  func stop() {
    timer?.cancel()
    timer = nil
  }

  // Markers (nspasteboard.org convention) that password managers and similar
  // tools set so clipboard utilities skip the content. We honor them so secrets
  // are never cached in history or sent over the tunnel.
  private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
  ]

  private func poll() {
    let snapshot = state.snapshot()
    if snapshot.syncPaused { return }

    let (text, isSensitive) = DispatchQueue.main.sync { () -> (String?, Bool) in
      let pasteboard = NSPasteboard.general
      let sensitive = (pasteboard.types ?? []).contains { Self.sensitiveTypes.contains($0) }
      return (pasteboard.string(forType: .string), sensitive)
    }

    if isSensitive { return }
    guard let text, !text.isEmpty else { return }
    if text.utf8.count > config.maxClipSizeBytes { return }
    if text != snapshot.lastSeenLocalClip {
      NSLog("[clipboard] New Mac clipboard detected (\(text.utf8.count) bytes)")
      state.updateMacClipboard(text)
    }
  }
}
